apiVersion: v1
kind: Secret
metadata:
  name: bank-mysql-secret
type: Opaque
data:
  MYSQL_DATABASE: {{ .Values.mysql.database | b64enc | quote }}
  MYSQL_USER: {{ .Values.mysql.user | b64enc | quote }}
  MYSQL_PASSWORD: {{ .Values.mysql.password | b64enc | quote }}
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.rootPassword | b64enc | quote }}
