apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank-mysql
  template:
    metadata:
      labels:
        app: bank-mysql
    spec:
      containers:
        - name: mysql
          image: {{ .Values.mysql.image }}
          args:
            - "--default-authentication-plugin={{ .Values.mysql.authPlugin }}"
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_HOST
              value: "%"
          envFrom:
            - secretRef:
                name: bank-mysql-secret
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
            - name: initdb
              mountPath: /docker-entrypoint-initdb.d/01-init-user.sql
              subPath: 01-init-user.sql  
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: bank-mysql-pvc
        - name: initdb
          configMap:
            name: bank-mysql-init
