apiVersion: v1
kind: Service
metadata:
  name: bank-app-cd
spec:
  type: {{ .Values.service.type }}
  selector:
    app: bank-app-cd
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}